### ISSUE TITLE
Please add the FreeBSD support

### ISSUE THREAD

**Issue by drook** [Azure/azure-storage-fuse#348]
Any chance this will someday be buildable under FreeBSD, which also has the FUSE stack ?

**Comment by amnguye** [comment]
Hi,

Support for FreeBSD is currently not on the roadmap for blobfuse. We are open to feedback and looking into it if the interest in this becomes larger.

For now you can clone the repository and try to build it for FreeBSD for now. We will try to assist you in trying to build this for blobfuse.

**Comment by drook** [comment]
Well, I was able to build it successfully with gcc8, with a minor patch that replaces canonicalize_file_name() to realpath(), and having gcc8-built boost (otherwise it either doesn't build with clang or cannot crossmap symbols when using clang-built boost), but then, unfortunately it doesn't work for some reason. I mean it doesn't crash, it starts and then "mounts" (at least does some syscalls and the kernel is showing me that /dev/fuse is mounted to /foot/bar) something, but the mountpoint is dead. No errors logged in kernel msg buffer or in system logs.

Well, I guess this is it.

**Comment by drook** [comment]
Follow-up: no, I'm mistaken, it does crash when trying to cwd/touch:

````shell
[root@calypso:/mnt]#
[root@calypso:azure-storage-fuse-1.1.1/build]# ./blobfuse /mnt/azure --tmp-path=/usr/tmp --container-name=calypso --log-level=LOG_DEBUG --use-https=true
[root@calypso:azure-storage-fuse-1.1.1/build]# cd /mnt/azure
[root@calypso:/mnt/azure]# touch test.txt
touch: test.txt: Input/output error
[root@calypso:/mnt/azure]# dmesg
pid 26755 (blobfuse), jid 0, uid 0: exited on signal 6 (core dumped)
[root@calypso:/mnt/azure]#
````

````gdb
[root@calypso:azure-storage-fuse-1.1.1/build]# /usr/libexec/gdb blobfuse /blobfuse.core
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /usr/home/emz/src/azure-storage-fuse-1.1.1/build/blobfuse]

Core was generated by `./blobfuse /mnt/azure --tmp-path=/usr/tmp --container-name=calypso --log-level=L'.
Program terminated with signal 6, Aborted.
Reading symbols from /lib/libthr.so.3...Reading symbols from /usr/lib/debug//lib/libthr.so.3.debug...done.
done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /usr/local/lib/libcurl.so.4...done.
Loaded symbols for /usr/local/lib/libcurl.so.4
Reading symbols from /usr/local/lib/libgnutls.so.30...done.
Loaded symbols for /usr/local/lib/libgnutls.so.30
Reading symbols from /usr/local/lib/libuuid.so.1...done.
Loaded symbols for /usr/local/lib/libuuid.so.1
Reading symbols from /usr/local/lib/libfuse.so.2...done.
Loaded symbols for /usr/local/lib/libfuse.so.2
Reading symbols from /usr/local/lib/libgcrypt.so.20...done.
Loaded symbols for /usr/local/lib/libgcrypt.so.20
Reading symbols from /usr/local/lib/gcc8/libstdc++.so.6...done.
Loaded symbols for /usr/local/lib/gcc8/libstdc++.so.6
Reading symbols from /lib/libm.so.5...Reading symbols from /usr/lib/debug//lib/libm.so.5.debug...done.
done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /lib/libgcc_s.so.1...Reading symbols from /usr/lib/debug//lib/libgcc_s.so.1.debug...done.
done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib/libc.so.7...BFD: /lib/libc.so.7: invalid relocation type 37
BFD: BFD 2.17.50 [FreeBSD] 2007-07-03 assertion fail /usr/src/gnu/usr.bin/binutils/libbfd/../../../../contrib/binutils/bfd/elf64-x86-64.c:276
Reading symbols from /usr/lib/debug//lib/libc.so.7.debug...done.
done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /usr/local/lib/libnghttp2.so.14...done.
Loaded symbols for /usr/local/lib/libnghttp2.so.14
Reading symbols from /usr/local/lib/libidn2.so.0...done.
Loaded symbols for /usr/local/lib/libidn2.so.0
Reading symbols from /usr/lib/libssl.so.111...Reading symbols from /usr/lib/debug//usr/lib/libssl.so.111.debug...done.
done.
Loaded symbols for /usr/lib/libssl.so.111
Reading symbols from /usr/lib/libheimntlm.so.11...Reading symbols from /usr/lib/debug//usr/lib/libheimntlm.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libheimntlm.so.11
Reading symbols from /usr/lib/libhx509.so.11...Reading symbols from /usr/lib/debug//usr/lib/libhx509.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libhx509.so.11
Reading symbols from /usr/lib/libcom_err.so.5...Reading symbols from /usr/lib/debug//usr/lib/libcom_err.so.5.debug...done.
done.
Loaded symbols for /usr/lib/libcom_err.so.5
Reading symbols from /lib/libcrypto.so.111...Reading symbols from /usr/lib/debug//lib/libcrypto.so.111.debug...done.
done.
Loaded symbols for /lib/libcrypto.so.111
Reading symbols from /usr/lib/libasn1.so.11...Reading symbols from /usr/lib/debug//usr/lib/libasn1.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libasn1.so.11
Reading symbols from /usr/lib/libwind.so.11...Reading symbols from /usr/lib/debug//usr/lib/libwind.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libwind.so.11
Reading symbols from /usr/lib/libheimbase.so.11...Reading symbols from /usr/lib/debug//usr/lib/libheimbase.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libheimbase.so.11
Reading symbols from /usr/lib/libroken.so.11...Reading symbols from /usr/lib/debug//usr/lib/libroken.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libroken.so.11
Reading symbols from /lib/libcrypt.so.5...Reading symbols from /usr/lib/debug//lib/libcrypt.so.5.debug...done.
done.
Loaded symbols for /lib/libcrypt.so.5
Reading symbols from /lib/libz.so.6...Reading symbols from /usr/lib/debug//lib/libz.so.6.debug...done.
done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /usr/lib/libkrb5.so.11...Reading symbols from /usr/lib/debug//usr/lib/libkrb5.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libkrb5.so.11
Reading symbols from /usr/lib/libgssapi.so.10...Reading symbols from /usr/lib/debug//usr/lib/libgssapi.so.10.debug...done.
done.
Loaded symbols for /usr/lib/libgssapi.so.10
Reading symbols from /usr/lib/libgssapi_krb5.so.10...Reading symbols from /usr/lib/debug//usr/lib/libgssapi_krb5.so.10.debug...done.
done.
Loaded symbols for /usr/lib/libgssapi_krb5.so.10
Reading symbols from /usr/local/lib/libp11-kit.so.0...done.
Loaded symbols for /usr/local/lib/libp11-kit.so.0
Reading symbols from /usr/local/lib/libunistring.so.2...done.
Loaded symbols for /usr/local/lib/libunistring.so.2
Reading symbols from /usr/lib/libdl.so.1...Reading symbols from /usr/lib/debug//usr/lib/libdl.so.1.debug...done.
done.
Loaded symbols for /usr/lib/libdl.so.1
Reading symbols from /usr/local/lib/libtasn1.so.6...done.
Loaded symbols for /usr/local/lib/libtasn1.so.6
Reading symbols from /usr/local/lib/libnettle.so.7...done.
Loaded symbols for /usr/local/lib/libnettle.so.7
Reading symbols from /usr/local/lib/libhogweed.so.5...done.
Loaded symbols for /usr/local/lib/libhogweed.so.5
Reading symbols from /usr/local/lib/libgmp.so.10...done.
Loaded symbols for /usr/local/lib/libgmp.so.10
Reading symbols from /usr/local/lib/libgpg-error.so.0...done.
Loaded symbols for /usr/local/lib/libgpg-error.so.0
Reading symbols from /usr/lib/libprivateheimipcc.so.11...Reading symbols from /usr/lib/debug//usr/lib/libprivateheimipcc.so.11.debug...done.
done.
Loaded symbols for /usr/lib/libprivateheimipcc.so.11
Reading symbols from /usr/local/lib/libffi.so.6...done.
Loaded symbols for /usr/local/lib/libffi.so.6
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/nss_ldap.so.1...done.
Loaded symbols for /usr/local/lib/nss_ldap.so.1
Reading symbols from /libexec/ld-elf.so.1...Reading symbols from /usr/lib/debug//libexec/ld-elf.so.1.debug...done.
done.
Loaded symbols for /libexec/ld-elf.so.1
#0  kill () at kill.S:3
3       RSYSCALL(kill)
[New Thread 803302a00 (LWP 102003/<unknown>)]
[New Thread 803302500 (LWP 102000/<unknown>)]
[New Thread 802b4dc00 (LWP 101939/<unknown>)]
[New Thread 802b4a000 (LWP 102699/<unknown>)]
(gdb) bt
#0  kill () at kill.S:3
#1  0x000000080161a680 in __fail (msg=<value optimized out>) at /usr/src/lib/libc/secure/stack_protector.c:110
#2  0x000000080161a5f0 in __stack_chk_fail () at /usr/src/lib/libc/secure/stack_protector.c:117
#3  0x0000000800d968ec in fuse_new_compat25 () from /usr/local/lib/libfuse.so.2
#4  0x0000000000000000 in ?? ()
Current language:  auto; currently asm
(gdb)
````

**Comment by vibhansa-msft** [comment]
We do not have any plan to support blobfuse on FreeBSD.
However, if this request is still open, we have recently previewed next generation of blobfuse. 
Can you give that a try on your setup and let us know how it goes?

**Comment by vibhansa-msft** [comment]
Closing this as BSD support is not our todo list for now.
